# Monitoring Configuration Section
# All monitoring-related settings are stored here
[monitoring]

# Prometheus Server URL
# Python scripts use this URL to fetch metrics
# Inside Docker network, "prometheus" resolves to Prometheus container
prometheus_url = http://prometheus:9090

# PromQL Query used to calculate CPU utilization
# Formula:
# 100 - Idle CPU %
#
# Example:
# Idle CPU = 98%
#
# CPU Usage = 100 - 98
# CPU Usage = 2%
query = 100 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100

# Slack Incoming Webhook URL
# Used for sending anomaly notifications
# Replace with actual Slack Webhook URL
slack_webhook = YOUR_SLACK_WEBHOOK_URL