# Copyright (c) 2026 cloudhiredofficial
# All rights reserved.

# Load saved ML model (.joblib file)
import joblib

# Used to call Prometheus API and Slack Webhook API
import requests

# Numerical processing library
# Not currently used in this script but often used in ML projects
import numpy as np

# Used to pause execution between monitoring cycles
import time

# Used for file existence checks
import os

# Used to read configuration from config.ini
import configparser

# Create configuration parser object
config = configparser.ConfigParser()

# Read config.ini file
config.read('config.ini')

# ML model file generated by train_model.py
MODEL_FILE = "aiops_model.joblib"

# Prometheus URL from config.ini
PROM_URL = config['monitoring']['prometheus_url']

# PromQL query from config.ini
QUERY = config['monitoring']['query']

# Slack Webhook URL from config.ini
SLACK_WEBHOOK = config['monitoring']['slack_webhook']


# Function to fetch current CPU utilization from Prometheus
def get_cpu():
    try:

        # Call Prometheus Instant Query API
        response = requests.get(

            # Example:
            # http://prometheus:9090/api/v1/query
            f"{PROM_URL}/api/v1/query",

            # Send PromQL query
            params={"query": QUERY},

            # Wait maximum 5 seconds
            timeout=5
        )

        # Raise exception if API returns 404/500/etc
        response.raise_for_status()

        # Convert JSON response into Python dictionary
        data = response.json()

        # Extract CPU value from Prometheus response
        # Example response:
        # data["data"]["result"][0]["value"][1] = "2.15"
        return float(data["data"]["result"][0]["value"][1])

    except Exception as e:

        # Print error if API call fails
        print(f"⚠️ Fetch error: {str(e)}")

        # Return None if CPU value unavailable
        return None


# Function to send Slack alert
def alert_slack(message):
    try:

        # Send POST request to Slack Webhook
        requests.post(

            # Slack Incoming Webhook URL
            SLACK_WEBHOOK,

            # Message payload
            json={"text": message},

            # Wait maximum 5 seconds
            timeout=5
        )

        # Success message
        print("✅ Slack alert sent")

    except Exception as e:

        # Print Slack API errors
        print(f"⚠️ Slack alert failed: {str(e)}")


# Entry point of script
if __name__ == "__main__":

    # Check whether ML model exists
    if not os.path.exists(MODEL_FILE):

        # Stop execution if model missing
        exit("❌ Model file not found - run train_model.py first")

    # Check whether config.ini exists
    if not os.path.exists('config.ini'):

        # Stop execution if config missing
        exit("❌ config.ini not found")

    # Warn if webhook not configured
    if SLACK_WEBHOOK == "YOUR_SLACK_WEBHOOK_URL":

        print("⚠️ Warning: Please configure Slack webhook in config.ini")

    # Load trained ML model from disk
    model = joblib.load(MODEL_FILE)

    # Startup message
    print("✅ AIOps detector started. Monitoring CPU...")

    # Infinite monitoring loop
    while True:

        # Fetch current CPU utilization
        cpu = get_cpu()

        # Continue only if CPU value received successfully
        if cpu is not None:

            # Pass CPU value to Isolation Forest model
            # Example:
            # [[2.15]]
            pred = model.predict([[cpu]])

            # Isolation Forest returns:
            # -1 = Anomaly
            #  1 = Normal
            if pred[0] == -1:

                # Create anomaly message
                msg = f"🚨 CPU Anomaly Detected: {cpu:.2f}%"

                # Print locally
                print(msg)

                # Send Slack notification
                alert_slack(msg)

            else:

                # Normal CPU behavior
                print(f"✅ CPU Normal: {cpu:.2f}%")

        # Wait 30 seconds before next check
        time.sleep(30)