# Copyright (c) 2026 cloudhiredofficial
# All rights reserved.

# Pandas library used for reading and processing CSV files
import pandas as pd

# Isolation Forest algorithm used for anomaly detection
# This is the Machine Learning model used in this project
from sklearn.ensemble import IsolationForest

# Used to save trained ML model into a file
import joblib

# Used for file existence checks
import os


# Function responsible for training the ML model
def train_model():
    try:

        # Verify training dataset exists
        # Generated by fetch_metrics.py
        if not os.path.exists("cpu_metrics.csv"):
            raise FileNotFoundError(
                "cpu_metrics.csv not found - run fetch_metrics.py first"
            )

        # Read historical CPU metrics from CSV file
        df = pd.read_csv("cpu_metrics.csv")

        # Ensure enough training data exists
        # Isolation Forest needs sufficient samples to learn patterns
        if len(df) < 10:
            raise ValueError(
                "Not enough data points (minimum 10 required)"
            )

        # Check for missing CPU values
        # Prevents training failures and inaccurate models
        if df["cpu_usage"].isnull().any():
            raise ValueError(
                "Missing values in CPU usage data"
            )

        # Create Isolation Forest model
        model = IsolationForest(

            # Assume approximately 5% of data may be anomalies
            contamination=0.05,

            # Fixed seed for reproducible results
            random_state=42,

            # Number of decision trees used by Isolation Forest
            n_estimators=100,

            # Automatically determine number of samples
            # used for training each tree
            max_samples='auto'
        )

        # Train model using CPU usage values
        # reshape(-1,1) converts:
        #
        # [1.2,1.5,1.8]
        #
        # into:
        #
        # [[1.2],
        #  [1.5],
        #  [1.8]]
        #
        # which is required by Scikit-Learn
        model.fit(
            df["cpu_usage"].values.reshape(-1, 1)
        )

        # Save trained model to disk
        # Output file:
        # aiops_model.joblib
        joblib.dump(
            model,
            "aiops_model.joblib"
        )

        # Success message
        print(
            "✅ Model trained and saved as aiops_model.joblib"
        )

    # Catch any training-related errors
    except Exception as e:

        print(
            f"❌ Training failed: {str(e)}"
        )


# Program entry point
if __name__ == "__main__":

    # Start ML model training process
    train_model()